### ISSUE TITLE
fork: Cannot allocate memory

### ISSUE THREAD

**Issue by zflamig** [Unidata/ldm-docker#39]
I am seeing
/home/ldm/bin/runldm.sh: fork: Cannot allocate memory
in my logs every so often followed by the container exiting. Any ideas what might be wrong?

Sometimes my VM (AWS EC2) completely hangs with ~30% CPU usage too (but no longer responds to ssh, etc and must be force restarted)

**Comment by julienchastang** [comment]
I have not seen this specifically, but I believe it. There are reports of Docker resource leaking (e.g., [eating up disk space](http://blog.eye48.com/post/98551740424/when-dockerio-eats-up-your-disc-space), CPU, etc.). I've run into these sorts of problems in other contexts. Sometimes I treat the VMs as throwaway and just fire up a new VM / Docker container. That's kind of ugly, but could be a stopgap solution until Docker matures. (I don't think Docker is mature, yet).

Can you give a bit more information such as:
  - The VM characteristics (memory, cores, etc. ) where you are running Docker
  - The Docker version (have you tried updating Docker, and all packages on your Linux VM -- e.g., `apt-get update` etc.?)
  - Whatever other information may be useful. Here is my [public-key](https://github.com/julienchastang.keys) if you want me to poke around your VM. Communicate to me privately the host and user name, if you want me to look.

All that said, I have been running this LDM Docker container in various clouds for months with no intervention from me.
