### ISSUE TITLE
Shared Memory Initialization - Permission Denied

### ISSUE THREAD

**Issue by four43** [Unidata/ldm-docker#45]
Hello all,

I thought I would start here to see if any docker specific users have seen this issue, then maybe jump upstream to LDM.

**It seems ldmd can't created shared memory for some reason?** Is that expected behavior in this environment?

ldmd.log:
```
...
20171120T203001.858358Z uldbutil[454] ERROR uldb.c:1071:sm_setShmId() Permission denied
20171120T203001.858410Z uldbutil[454] ERROR uldb.c:1071:sm_setShmId() Couldn't get shared-memory segment identifier
20171120T203001.858414Z uldbutil[454] ERROR uldb.c:1095:sm_attach() Couldn't get shared-memory segment
20171120T203001.858417Z uldbutil[454] ERROR uldb.c:1176:sm_init() Couldn't attach shared-memory segment
...
```

### System Info
```
# sysctl kernel.shmmax
kernel.shmmax = 18446744073692774399
```
```
# uname -a
Linux *****-aws #47-Ubuntu SMP Thu Sep 28 20:05:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
```
# docker --version
Docker version 17.09.0-ce, build afdb6d4
```
```
# docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
unidata/ldm-docker   6.13.6              3f3ace8d5649        9 months ago        460MB
```

**Comment by julienchastang** [comment]
I had intended on responding to this issues sooner, but then forgot about it. I see you are running the LDM container on AWS. I've run this container on a couple of different clouds without issue: Azure, Openstack. The root problem is a "permission denied" error. Are you running Docker on AWS with a privileged or root user? I unfortunately do not have many suggestions beyond that.

**Comment by four43** [comment]
Yeah it's on AWS, the container is started via a `systemd` service. It should have run the docker run command as root. 

From what I can tell this hasn't had any ill effects on our system and things are working on our end. I was just curious as to what may have caused it. We'll see if anyone else has this issue. My knowledge of this is quite limited and since it isn't blocking for us I'm not super motivated to further diagnose.

Thanks for your help.

**Comment by julienchastang** [comment]
Just to be clear, does the container work in spite of the distracting error messages?

**Comment by four43** [comment]
It does for our use case. What we're doing is pretty simple though, we aren't using any of the auto-cleanup functionality (`scour`), just listening to a stream, piping it to a script. `pqact` is only sending metrics.

Container runs, does what we need it to do.

Thanks.
