### ISSUE TITLE
"ldmadmin watch" runs very slow

### ISSUE THREAD

**Issue by pagecp** [Unidata/ldm-docker#73]
I am running an ldm container, and ldmadmin watch runs very slowly.
It also takes forever to react to ctrl-C or ctrl-D to end the process.

I tried both executing the command inside a bash:
docker exec -ti 64530d3aa377 bash
then 
ldmadmin watch

or launching the command directly:
docker exec -ti 64530d3aa377 ldmadmin watch
but the results are the same...

**Comment by tyoksas** [comment]
There are a couple reasons why the output from 'ldmadmin watch' might be slow:

- there are very few products in the feed(s) being watched

- the network connection from the upstream to the LDM in the container is very slow

Questions:

- what is the upstream machine(s) that your dockerized LDM is REQUESTing from?

- what feed(s) are you REQUESTing?

- is your LDM reporting real-time statistics back to us?

  This is enabled by making sure that the LDM configuration line 'EXEC rtstats'
  is not commented.

- should the feed(s) you are REQUESTing contain a high number of products?

We do not believe that the dockerization of the LDM would be the cause of slow
output from 'ldmadmin watch'; we do not experience this in the dockerized LDM
containers that we run.

**Comment by pagecp** [comment]
Thanks for your fast reply. In fact after investigating, it was due to the fact that the ldm.pq queue file was on an NFS disk instead of a local disk. Of course this generated a large latency! This was not intended and I fixed the issue.

**Comment by julienchastang** [comment]
That is good diagnostic information. Thanks for letting us know.
