### ISSUE TITLE
Add check for existing product queue in runldm.sh

### ISSUE THREAD

**Issue by CameronLP** [Unidata/ldm-docker#74]
Hello,

I am running the LDM container with /home/ldm/var/queues/ directory set up as a volume mount to the host. This allows for the product queue to be stored in a persistent location. Currently, runldm.sh creates a new product queue every time the LDM container starts up:
```
ldmadmin clean
ldmadmin delqueue
ldmadmin mkqueue
ldmadmin start
```
I would like to suggest adding a check for an existing product queue similar to this:
```
regutil -s docker.localhost.local /hostname

if [ ! -f /home/ldm/var/queues/ldm.pq ] ; then
    echo "The product queue file home/ldm/var/queues/ldm.pq does not exist. Making new queue."
    ldmadmin mkqueue
else
    # queue exists, test queue "sanity"
    echo "Checking existing product queue with 'pqcat'"
    pqcat -l- -s && pqcheck -F
    if test $? != 0
    then
        echo "Product queue appears corrupt. Deleting and rebuilding."
        ldmadmin delqueue
        ldmadmin mkqueue
    else
        echo "Using existing LDM product queue."
    fi
fi

# In case of unclean shutdown, remove pid and lck files
echo "Running 'ldmadmin clean'."
ldmadmin clean
echo "Starting LDM..."
ldmadmin start
echo "LDM is running."
```
Adding a check would make it possible to restart the LDM container without needing to create a new queue each time.

Thanks!

**Comment by julienchastang** [comment]
Hi @CameronLP. First, sorry for the really long delay. I had not forgotten about this but I got sidetracked by the holidays and conferences and I have been dealing with a bit of a backlog since that time. I vetted your proposal with Tom and it looks good. Do you think you could submit this as a PR? There are a few very minor alterations that can be made to your suggested improvements. We could iterate on that. But basically, overall, this looks good. Thanks for your input.

**Comment by julienchastang** [comment]
I would do:

```
regutil -s docker.localhost.local /hostname

if [ ! -f /home/ldm/var/queues/ldm.pq ]
then
    echo "The product queue file home/ldm/var/queues/ldm.pq does not exist. Making new queue."
    ldmadmin mkqueue
else
    # queue exists, test queue "sanity"
    echo "Checking existing product queue with 'pqcat'"
    pqcat -l- -s && pqcheck -F
    if [ $? -eq 0 ]
    then
        echo "Using existing LDM product queue."
    else
        echo "Product queue appears corrupt. Deleting and rebuilding."
        ldmadmin delqueue
        ldmadmin mkqueue
    fi
fi

# In case of unclean shutdown, remove pid and lck files
echo "Running 'ldmadmin clean'."
ldmadmin clean
echo "Starting LDM..."
ldmadmin start
echo "LDM is running."
```

I just tried to clean up the bash a bit to make the two `if` blocks consistent with modern bash practice — or what I believe to be the case. Does that look right to you? I did not test this.

**Comment by CameronLP** [comment]
> I would do:
> 
> ```
> regutil -s docker.localhost.local /hostname
> 
> if [ ! -f /home/ldm/var/queues/ldm.pq ]
> then
>     echo "The product queue file home/ldm/var/queues/ldm.pq does not exist. Making new queue."
>     ldmadmin mkqueue
> else
>     # queue exists, test queue "sanity"
>     echo "Checking existing product queue with 'pqcat'"
>     pqcat -l- -s && pqcheck -F
>     if [ $? -eq 0 ]
>     then
>         echo "Using existing LDM product queue."
>     else
>         echo "Product queue appears corrupt. Deleting and rebuilding."
>         ldmadmin delqueue
>         ldmadmin mkqueue
>     fi
> fi
> 
> # In case of unclean shutdown, remove pid and lck files
> echo "Running 'ldmadmin clean'."
> ldmadmin clean
> echo "Starting LDM..."
> ldmadmin start
> echo "LDM is running."
> ```
> 
> I just tried to clean up the bash a bit to make the two `if` blocks consistent with modern bash practice — or what I believe to be the case. Does that look right to you? I did not test this.

Looks good. I tested it in two containers (one with an existing product queue mounted and one without) and in both cases the containers started up as expected. Just updated pull request #76 with the changes.
