### ISSUE TITLE
Install procps package in Dockerfile

### ISSUE THREAD

**Issue by ana-v-espinoza** [Unidata/ldm-docker#98]
When running `ldmadmin pqactHUP` from within the Docker container as the `ldm` user to re-read pqact files, the following error occurs:
`ldmadmin_pqactHUP: Cannot open ps(1)`

This is because the `rockylinux` image that `ldm-docker` is based on is stripped down and doesn't have the `ps` program. Install it with a `yum install -y procps`

**Comment by julienchastang** [comment]
`ps` should now be available.
